### PR TITLE
Join monster v3

### PR DESCRIPTION
**Pull request by S-Stephen**
The syntax for v3 Join Monster requires that config is included in a

extensions {
   JoinMonster {

block

The adapter should still work as was with Join Monster < 3

### CODE REVIEW

**Comment by lorensr** [comment]
Thanks! Would you mind updating https://github.com/join-monster/join-monster-graphql-tools-adapter/blob/master/src/index.test.js ?

**Comment by lorensr** [comment]
Thanks for adding! From the snapshot, it looks like it's failing:

image

**Comment by S-Stephen** [comment]
Hi,

I ended up replacing the tests for the 'old' syntax, as I couldn't figure out how to test against both JoinMonster versions

I also added a nagging process message in the adapter - not sure whether it's called for? 

Hope it now works!

**Comment by lorensr** [comment]
`npm test` is still failing for me due to the same AssertionError—is it giving you a different result?

```
$ npm test

> join-monster-graphql-tools-adapter@0.1.0 test /Users/me/gh/join-monster-graphql-tools-adapter
> jest

 FAIL  src/index.test.js
  ✕ works (29ms)

  ● works

    expect(received).toMatchSnapshot()

    Snapshot name: `works 1`

    - Snapshot  - 43
    + Received  +  3

      Object {
        "data": Object {
    -     "user": Object {
    -       "email": "andrew@stem.is",
    -       "fullName": "andrew carlson",
    -       "id": 1,
    -       "posts": Array [
    -         Object {
    -           "body": "Check out this cool new GraphQL library, Join Monster.",
    -           "comments": Array [
    -             Object {
    -               "archived": false,
    -               "authorId": 1,
    -               "body": "Do not forget to check out the demo.",
    -               "id": 4,
    -             },
    -             Object {
    -               "archived": false,
    -               "authorId": 3,
    -               "body": "This sucks. Go use REST you scrub.",
    -               "id": 5,
    +     "user": null,
        },
    -             Object {
    -               "archived": false,
    -               "authorId": 1,
    -               "body": "Also, submit a PR if you have a feature you want to add.",
    -               "id": 6,
    -             },
    -             Object {
    -               "archived": true,
    -               "authorId": 2,
    -               "body": "FIRST COMMENT!",
    -               "id": 7,
    -             },
    -             Object {
    -               "archived": false,
    -               "authorId": 1,
    -               "body": "Somebody please help me with this library. It is so much work.",
    -               "id": 8,
    -             },
    -           ],
    -           "id": 2,
    -           "numComments": 5,
    -         },
    +   "errors": Array [
    +     [GraphQLError: Unexpected error value: { generatedMessage: false, name: "AssertionError [ERR_ASSERTION]", code: "ERR_ASSERTION", actual: false, expected: true, operator: "==" }],
        ],
    -     },
    -   },
      }

      188 |   await db.open(path.join(__dirname, '..', 'db', 'test1-data.sl3'))
      189 |   const res = await graphql(schema, query)
    > 190 |   expect(res).toMatchSnapshot()
          |               ^
      191 | })

      at Object.it (src/index.test.js:190:15)

 › 1 snapshot failed.
Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `npm test -- -u` to update them.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   1 failed, 1 total
Time:        1.315s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by S-Stephen** [comment]
I've added a Github action that should run the tests.  You may want to restrict this to run on master branch.  It appears to work in my repo?!

**Comment by lorensr** [comment]
Thank you! Published in `0.1.1`

**Pull request merged**
